# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "ubuntu/jammy64"
  config.vm.box = "cloud-image/ubuntu-24.04"
  # Shared folder to exchange swarm tokens
  config.vm.synced_folder "./03", "/home/vagrant/03", create: true
  config.vm.synced_folder "./02/",  "/home/vagrant/02",  create: true
  config.vm.synced_folder "./01/",  "/home/vagrant/dcompose",  create: true
  config.vm.synced_folder "./services", "/home/vagrant/services", create: true

  # Common Provider Configuration
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end

  # Manager Node
  config.vm.define "manager01" do |manager|
    manager.vm.hostname = "manager01"
    manager.vm.network "private_network", ip: "192.168.56.10"
    manager.vm.provision "shell", path: "./02/setup.sh"
    manager.vm.provision "shell", path: "./03/swarm_init.sh"
    

  end

  # Worker 01
  config.vm.define "worker01" do |worker|
    worker.vm.hostname = "worker01"
    worker.vm.network "private_network", ip: "192.168.56.11"
    worker.vm.provision "shell", path: "./02/setup.sh"
    worker.vm.provision "shell", path: "./03/swarm_join_w1.sh"
  end

  # Worker 02
  config.vm.define "worker02" do |worker|
    worker.vm.hostname = "worker02"
    worker.vm.network "private_network", ip: "192.168.56.12"
    worker.vm.provision "shell", path: "./02/setup.sh"
    worker.vm.provision "shell", path: "./03/swarm_join_w2.sh"
  end
end
